// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addUrlStmt, err = db.PrepareContext(ctx, addUrl); err != nil {
		return nil, fmt.Errorf("error preparing query AddUrl: %w", err)
	}
	if q.getUrlStmt, err = db.PrepareContext(ctx, getUrl); err != nil {
		return nil, fmt.Errorf("error preparing query GetUrl: %w", err)
	}
	if q.getUrlHashStmt, err = db.PrepareContext(ctx, getUrlHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetUrlHash: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addUrlStmt != nil {
		if cerr := q.addUrlStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUrlStmt: %w", cerr)
		}
	}
	if q.getUrlStmt != nil {
		if cerr := q.getUrlStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUrlStmt: %w", cerr)
		}
	}
	if q.getUrlHashStmt != nil {
		if cerr := q.getUrlHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUrlHashStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db             DBTX
	tx             *sql.Tx
	addUrlStmt     *sql.Stmt
	getUrlStmt     *sql.Stmt
	getUrlHashStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:             tx,
		tx:             tx,
		addUrlStmt:     q.addUrlStmt,
		getUrlStmt:     q.getUrlStmt,
		getUrlHashStmt: q.getUrlHashStmt,
	}
}
