// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgres

import (
	"time"
)

type Url struct {
	ID        int64     `json:"id"`
	Url       string    `json:"url"`
	Hash      string    `json:"hash"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
