// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgres

import (
	"context"
)

type Querier interface {
	AddUrl(ctx context.Context, arg AddUrlParams) (Url, error)
	GetUrl(ctx context.Context, hash string) (Url, error)
	GetUrlHash(ctx context.Context, url string) (Url, error)
}

var _ Querier = (*Queries)(nil)
